config/routes.rb
SwaggerDocsSample::Application.routes.draw do

  resources :banos

  post '/WC' => 'banos#crearPunto'
  get '/WC' => 'banos#obtieneTodos'

  get '/calcula' => 'coordenada#obtieneCercanos'

  root 'welcome#index'

  

end

app/models/bano.rb
class Bano < ActiveRecord::Base
end

app/models/operacionGps.rb
class OperacionGps 


def initialize()
	end

	def calculaZonaHoraria(longitud)
     zonaHoraria = longitud.to_f / 15
     return zonaHoraria.to_i
  end


  def calculaDistancia(latitudO,longitudO, latitudD, longitudD) 

	

    	#Se covierte a radianes

    	latitudR = latitudO.to_f * (Math::PI / 180);
    	longitudR = longitudO.to_f * (Math::PI / 180);


    	latitudR2 = latitudD * (Math::PI / 180);
    	longitudR2 = longitudD * (Math::PI / 180);


    	#Deltas de latitud y longitud

    	deltaLatitud = latitudR.to_f - latitudR2.to_f
    	deltaLongitud = longitudR.to_f - longitudR2.to_f


    	a1 = Math.sin(deltaLatitud/2)**2
    	a2 = Math.sin(deltaLongitud/2)**2


    	atotal = a1 + Math.cos(latitudR.to_f) * Math.cos(latitudR2.to_f) * a2;

    	c = 2 * Math.atan2(Math.sqrt(atotal), Math.sqrt(1-atotal))

    	d = 6371 * c;

    	return d
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banos_controller.rb
require "operacionGps.rb"

class BanosController < ApplicationController
  # before_action :set_bano, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token  

  swagger_controller :banos, "Baños"

  swagger_api :crearPunto do
    summary "Crear posición de los baños"
    param :form, :latitud, :float, :required, "Latitud"
    param :form, :longitud, :float, :required, "Longitud"
    param :form, :descripcion, :string, :required, "Descripción"
    response :json
    response :not_acceptable
  end

  swagger_api :obtieneTodos do
    summary "Obtiene todos los baños"
    response :json
    response :not_acceptable
  end

  swagger_api :modificaBaño do
    summary "Modifica la posicion de un baño"
    param :form, :latitud, :float, :required, "Latitud"
    param :form, :longitud, :float, :required, "Longitud"
    param :form, :descripcion, :string, :required, "Descripción"
    response :json
    response :not_acceptable
  end

  def crearPunto

    latitud = params[:latitud]
    longitud = params[:longitud]
    descripcion = params[:descripcion]

    logger.info("LATITUD: #{latitud}") 
    logger.info("LONGITUD: #{longitud}")
    logger.info("DESCRIPCION: #{descripcion}")

    operacionGps = OperacionGps.new

    zonaHor = operacionGps.calculaZonaHoraria(longitud)

    @banoNuevo = Bano.new
    @banoNuevo.latitud = latitud
    @banoNuevo.longitud = longitud
    @banoNuevo.descripcion = descripcion
    @banoNuevo.zonaHoraria = zonaHor

    if @banoNuevo.save 
      logger.info("SE GUARDO CORRECTAMENTE")
    else
      logger.info("NO SE PUDO GURDAR")
    end


    render :json => {result:"Success"}, :status => 200

  end


  def obtieneTodos
    @banos = Bano.all
    render :json => @banos.to_json, :callback => params['callback'], :status => 200
  end


  def modificaBaño

    latitud = params[:latitud]
    longitud = params[:longitud]
    descripcion = params[:descripcion]

    logger.info("LATITUD: #{latitud}") 
    logger.info("LONGITUD: #{longitud}")
    logger.info("DESCRIPCION: #{descripcion}")

    operacionGps = OperacionGps.new

    zonaHor = operacionGps.calculaZonaHoraria(longitud)

    @bano.update(bano_params)

  end








  # GET /banos
  # GET /banos.json
  def index
    @banos = Bano.all
  end

  # GET /banos/1
  # GET /banos/1.json
  def show
  end

  # GET /banos/new
  def new
    @bano = Bano.new
  end

  # GET /banos/1/edit
  def edit
  end

  # POST /banos
  # POST /banos.json
  def create
    @bano = Bano.new(bano_params)

    respond_to do |format|
      if @bano.save
        format.html { redirect_to @bano, notice: 'Bano was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bano }
      else
        format.html { render action: 'new' }
        format.json { render json: @bano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banos/1
  # PATCH/PUT /banos/1.json
  def update
    respond_to do |format|
      if @bano.update(bano_params)
        format.html { redirect_to @bano, notice: 'Bano was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banos/1
  # DELETE /banos/1.json
  def destroy
    @bano.destroy
    respond_to do |format|
      format.html { redirect_to banos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bano
      @bano = Bano.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bano_params
      params.require(:bano).permit(:descripcion, :latitud, :longitud)
    end
end

app/controllers/coordenada_controller.rb
require "operacionGps.rb"
class CoordenadaController < ApplicationController

	skip_before_filter :verify_authenticity_token  

	swagger_controller :coordenada, "Coordenadas"

	  swagger_api :obtieneCercanos do
	    summary "Obtiene los baños mas cercanos dependiendo de la posición"
	    param :form, :latitud, :string, :required, "Latitud"
	    param :form, :longitud, :string, :required, "Longitud"
	    param :form, :distancia, :string, "Distancia"
	    response :json
	    response :not_acceptable
	  end


	  def obtieneCercanos 

	  	latitud = params[:latitud]
    	longitud = params[:longitud]
    	distanciaParam = params[:distancia]
        operacionGps = OperacionGps.new

    	if !distanciaParam
    		distanciaParam = 5
    	end

         zonaHorariaCons = operacionGps.calculaZonaHoraria(longitud)

    	if distanciaParam.to_i > 0
    		
            #Obtener las ubicaciones con respecto a la zona horaria
	    	@Banos = Bano.where(zonaHoraria: zonaHorariaCons)
	    	# @Banos = Bano.all
            filtroBanos = Array.new

	    	@Banos.each do |bano|
	    		logger.info("Descripcion del Lugar : #{bano.descripcion}")
	    		distancia = operacionGps.calculaDistancia(latitud, longitud, bano.latitud, bano.longitud)
	    		logger.info("Distancia : #{distancia} kilometros")

	    		if distancia <= distanciaParam.to_i
	    			filtroBanos << bano
	    		end

	    	end

    	else
    		filtroBanos = "Distancia no permitida"
    	end

    	# logger.info("Todos los baños : #{@Banos}")

    	# distancia = calculaDistancia(latitud, longitud)


	  	render :json => filtroBanos, :callback => params['callback'], :status => 200
	  end


	


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banos_helper.rb
module BanosHelper
end

app/views/banos/_form.html.erb
<%= form_for(@bano) do |f| %>
  <% if @bano.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bano.errors.count, "error") %> prohibited this bano from being saved:</h2>

      <ul>
      <% @bano.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :latitud %><br>
    <%= f.text_field :latitud %>
  </div>
  <div class="field">
    <%= f.label :longitud %><br>
    <%= f.text_field :longitud %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banos/edit.html.erb
<h1>Editing bano</h1>

<%= render 'form' %>

<%= link_to 'Show', @bano %> |
<%= link_to 'Back', banos_path %>

app/views/banos/index.html.erb
<h1>Listing banos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @banos.each do |bano| %>
      <tr>
        <td><%= bano.descripcion %></td>
        <td><%= bano.latitud %></td>
        <td><%= bano.longitud %></td>
        <td><%= link_to 'Show', bano %></td>
        <td><%= link_to 'Edit', edit_bano_path(bano) %></td>
        <td><%= link_to 'Destroy', bano, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bano', new_bano_path %>

app/views/banos/new.html.erb
<h1>New bano</h1>

<%= render 'form' %>

<%= link_to 'Back', banos_path %>

app/views/banos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @bano.descripcion %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @bano.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @bano.longitud %>
</p>

<%= link_to 'Edit', edit_bano_path(@bano) %> |
<%= link_to 'Back', banos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwaggerDocsSample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>
	API
</h1>